logging:
  level:
    org.springframework.cloud.servicebroker: DEBUG
    org.springframework.boot: INFO

axway:
  apim:
    connect:
      timeout: 30000
    read:
      timeout: 30000
    orgname:
      prefix: TEST
spring:

  security:
    user:
      name: admin
      password: changeme
      roles:
        - ADMIN
    enable-csrf: false


  cloud:
    openservicebroker:
      api-version-check-enabled: false
      catalog:
        services:
          - id: ED01F448-40C7-4A9D-93D0-51E7D4E93CA1
            name: Axway-APIM
            description: Axway service broker implementation
            bindable: true

            tags:
              - Axway
              - api
              - API
              - api management
              - api platform
              - api gateway
              - Axway AMPLIFY
            metadata:
              longDescription: Axway Amplify APIM Service Broker,
              documentationUrl: https://github.com/Axway-API-Management-Plus,
              providerDisplayName: Axway,
              displayName: Axway Amplify APIM,
              imageUrl: https://cdn.axway.com/globalnav/axway-logo-top.svg,
              supportUrl: https://github.com/Axway-API-Management-Plus

            requires:
              - route_forwarding

            dashboard_client:
              id": id
              secret: secret,
              redirect_uri: https://axway.com

            plans:
              - id: 1A6C15A6-1DE1-4870-A4F2-EA0A905F4A0F
                name: APIM-Free
                description: This is a default Axway plan.  All services are created equally
                free: false
                metadata:
                  displayName: Standard
                  longDescription: Standard Plan
                  costs:
                    amount:
                      usd: 0.0
                    unit: MONTHLY
                  bullets:
                    - Routing
                    - Authentication
                    - Throtlling
              - id: 2A6C15A6-1DE1-4870-A4F2-EA0A905F4A0F
                name: APIM-Premium
                description: This is a Paid Axway Premium plan.  All services are created equally
                free: false
                metadata:
                  displayName: Standard
                  longDescription: Standard Plan
                  costs:
                    amount:
                      usd: 0.0
                    unit: MONTHLY
                  bullets:
                    - Routing
                    - Authentication
                    - Throtlling
